domain: rockstore.io

image: prod-comms.ps5.docker-registry.canonical.com/rockstore.io

env:
  - name: MAINTENANCE
    configMapKeyRef:
      key: maintenance
      name: rockstore

  - name: ENVIRONMENT
    configMapKeyRef:
      key: environment
      name: environment

extraHosts:
  - domain: jujucharms.com
  - domain: openoperatorcollection.io

# Overrides for staging environment
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    if ($host != 'staging.rockstore.io' ) {
      rewrite ^ https://staging.rockstore.io$request_uri? permanent;
    }
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";
