name: Deploy

on:
  push:
    branches:
      - main
      - staging
      - ps7-deployment
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (Production or Staging)'
        required: true
        type: choice
        options:
          - Production
          - Staging
      force_charm_build:
        description: 'True to force the charm build'
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setup-env.outputs.environment }}
      force_charm_build: ${{ steps.setup-env.outputs.force_charm_build }}
    steps:
      - name: Setup environment
        id: setup-env
        run: |
          env_from_input="${{ github.event.inputs.environment }}"
          env_from_branch=""
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            env_from_branch="Production"
          fi;
          environment="${env_from_input:-${env_from_branch:-Staging}}"
          echo "environment=$environment" >> $GITHUB_OUTPUT
          echo "force_charm_build=${{ github.event.inputs.force_charm_build || false }}" >> $GITHUB_OUTPUT

  # We need to output here the environment variables because the "environment" can not
  # be set in a reusable job (those with key "uses"), so we would not be able to retrieve
  # any environment-dependent variable in there
  setup:
    runs-on: ubuntu-latest
    needs: setenv
    environment: ${{ needs.setenv.outputs.environment }}
    outputs:
      environment_url: ${{ steps.setup-vars.outputs.environment_url }}
      charm_name: ${{ steps.setup-vars.outputs.charm_name }}
      channel: ${{ steps.setup-vars.outputs.channel }}
      terraform_dir: ${{ steps.setup-vars.outputs.terraform_dir }}
    steps:
      - name: Setup vars
        id: setup-vars
        run: |
          if [ "${{ needs.setenv.outputs.environment }}" = "Production" ]; then
            echo "terraform_dir=terraform/ps7/k8s-prod-marketplace" >> $GITHUB_OUTPUT
          else
            echo "terraform_dir=terraform/ps7/k8s-stg-marketplace" >> $GITHUB_OUTPUT
          fi;

          echo "environment_url=${{ vars.ENVIRONMENT_URL }}" >> $GITHUB_OUTPUT
          echo "charm_name=${{ vars.CHARM_NAME }}" >> $GITHUB_OUTPUT
          echo "channel=${{ vars.CHANNEL }}" >> $GITHUB_OUTPUT

  deploy:
    needs: [setenv, setup]
    name: Deploy
    uses: canonical/webteam-devops/.github/workflows/terraform-deploy-ps7.yaml@ps7-deployment
    permissions:
      packages: write
      id-token: write
      contents: read
    with:
      #environment: ${{ needs.setenv.outputs.environment }}
      #environment_url: ${{ needs.setup.outputs.environment_url }}
      charm_name: ${{ needs.setup.outputs.charm_name }}
      channel: ${{ needs.setup.outputs.channel }}
      #deploy_method: terraform
      terraform_dir: ${{ needs.setup.outputs.terraform_dir }}
      # Force conversion to boolean
      #force_charm_build: ${{ needs.setenv.outputs.force_charm_build == 'true' }}
      # tmp for running the script of terraform-deploy-ps7 directly
      # ver 6
      charm_revision: "1"
      resource_name: app-image
      resource_revision_number: "2"
    secrets:
      VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      #CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
